theme="hugo-blog-theme"
baseurl = "https://raul782.github.io"
languageCode = "en-us"
title = "Coding on the edge"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
#disqusShortname = "Your Disqus Name" # optional
copyright = "© 2015 Copyright Raul Rodriguez"

[params]
    description = "blog about symfony & devops" # optional
    twitter = "raul782" # optional
    github = "raul782" # optional
    #  facebook = "Your facebook Name" # optional
    gplus = "raul782" # optional
    #  linkedin = "raul782" # optional
    # headerCover = "images/headerCover.png" # optional
    footerCover = "images/footerCover.png" # optional
    googleAnalyticsUserID = "UA-72804365-1" # optional
    bggradient = "amber"

[permalinks]
    post = "/:year/:month/:day/:title/" # optional
